### PR TITLE
Add v1.4ᴮᴱᵀᴬ

### PR DESCRIPTION
**Pull request by WorriedArrow**
Adds version 1.4ᴮᴱᵀᴬ (Still unusable, doesn't actually launch minecraft).

### CODE REVIEW

**Comment by Lucas4545ah** [comment]
Whats the point? It could run minecraft before, why can't it now?

**Comment by Lucas4545ah** [comment]
**Other Items:**

> unwanted icon
> premade profiles are not wanted
> html written in a unreadable way
> inno setup is not made for electron
> conflicting versions, as 1.4 is for adding and modifying settings.

if you fix these problems, i will accept it.

**Comment by WorriedArrow** [comment]
are you sure that it could run lol
cause i have the original version and it opens console but doesnt run mc

**Comment by WorriedArrow** [comment]
also inno setup is fine for electron
vscode is packaged with it

**Comment by Lucas4545ah** [comment]
yes it does run
Capture

**Comment by Lucas4545ah** [comment]
#

> also inno setup is fine for electron vscode is packaged with it

It might **work**, but its not **made** for electron.

**Comment by WorriedArrow** [comment]
> yes it does run Capture
> 
> edit: make sure to make cli folder

well i think it didnt work on mine because i didnt have assets folder lol

**Comment by WorriedArrow** [comment]
alright working on launching minecraft right now.

**Comment by WorriedArrow** [comment]
i can use nsis, although this is not as simple.

**Comment by WorriedArrow** [comment]
> html written in a unreadable way
thats prettier not my fault lol ill disable the line breaks

**Comment by WorriedArrow** [comment]
lets goooo mc launches

**Pull request closed without merging**
